/* Curated airline list for the flight dropdown — common Asia-Pacific and
   long-haul carriers. "Other…" in the UI reveals a free-text fallback. */
export type Airline = { name: string; iata: string; icao: string };

export const AIRLINES: Airline[] = [
  { name: 'Philippine Airlines', iata: 'PR', icao: 'PAL' },
  { name: 'Cebu Pacific', iata: '5J', icao: 'CEB' },
  { name: 'AirAsia Philippines', iata: 'Z2', icao: 'APG' },
  { name: 'PAL Express', iata: '2P', icao: 'GAP' },
  { name: 'Cathay Pacific', iata: 'CX', icao: 'CPA' },
  { name: 'Hong Kong Express', iata: 'UO', icao: 'HKE' },
  { name: 'China Airlines', iata: 'CI', icao: 'CAL' },
  { name: 'EVA Air', iata: 'BR', icao: 'EVA' },
  { name: 'STARLUX Airlines', iata: 'JX', icao: 'SJX' },
  { name: 'Vietnam Airlines', iata: 'VN', icao: 'HVN' },
  { name: 'VietJet Air', iata: 'VJ', icao: 'VJC' },
  { name: 'Bamboo Airways', iata: 'QH', icao: 'BAV' },
  { name: 'Thai Airways', iata: 'TG', icao: 'THA' },
  { name: 'Thai AirAsia', iata: 'FD', icao: 'AIQ' },
  { name: 'Bangkok Airways', iata: 'PG', icao: 'BKP' },
  { name: 'Japan Airlines', iata: 'JL', icao: 'JAL' },
  { name: 'All Nippon Airways (ANA)', iata: 'NH', icao: 'ANA' },
  { name: 'Korean Air', iata: 'KE', icao: 'KAL' },
  { name: 'Asiana Airlines', iata: 'OZ', icao: 'AAR' },
  { name: 'Air China', iata: 'CA', icao: 'CCA' },
  { name: 'China Eastern', iata: 'MU', icao: 'CES' },
  { name: 'China Southern', iata: 'CZ', icao: 'CSN' },
  { name: 'Air Astana', iata: 'KC', icao: 'KZR' },
  { name: 'Uzbekistan Airways', iata: 'HY', icao: 'UZB' },
  { name: 'Air Manas', iata: 'MZ', icao: 'AVJ' },
  { name: 'Singapore Airlines', iata: 'SQ', icao: 'SIA' },
  { name: 'Scoot', iata: 'TR', icao: 'TGW' },
  { name: 'AirAsia (Malaysia)', iata: 'AK', icao: 'AXM' },
  { name: 'Malaysia Airlines', iata: 'MH', icao: 'MAS' },
  { name: 'Emirates', iata: 'EK', icao: 'UAE' },
  { name: 'Qatar Airways', iata: 'QR', icao: 'QTR' },
  { name: 'Etihad Airways', iata: 'EY', icao: 'ETD' },
  { name: 'Turkish Airlines', iata: 'TK', icao: 'THY' },
  { name: 'United Airlines', iata: 'UA', icao: 'UAL' },
  { name: 'American Airlines', iata: 'AA', icao: 'AAL' },
  { name: 'Delta Air Lines', iata: 'DL', icao: 'DAL' },
  { name: 'Air Canada', iata: 'AC', icao: 'ACA' },
  { name: 'British Airways', iata: 'BA', icao: 'BAW' },
  { name: 'Lufthansa', iata: 'LH', icao: 'DLH' },
  { name: 'Air France', iata: 'AF', icao: 'AFR' },
  { name: 'KLM', iata: 'KL', icao: 'KLM' },
  { name: 'Qantas', iata: 'QF', icao: 'QFA' },
];
