-- TrailMate — Storage buckets and object policies (SDS §3.1: photos, GPX, waiver PDFs)
--
-- Path convention is enforced by policy, because storage.objects has no foreign keys:
--   avatars/{user_id}/{file}
--   hike-photos/{hike_id}/{file}
--   gpx/{hike_id}/{file}
--   waivers/{user_id}/{waiver_id}.pdf     (private, signed URLs only)

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('avatars',     'avatars',     true,  5 * 1024 * 1024,
     array['image/jpeg', 'image/png', 'image/webp', 'image/heic']),
  ('hike-photos', 'hike-photos', true,  10 * 1024 * 1024,
     array['image/jpeg', 'image/png', 'image/webp', 'image/heic']),
  ('gpx',         'gpx',         true,  5 * 1024 * 1024,
     array['application/gpx+xml', 'application/xml', 'text/xml', 'application/octet-stream']),
  ('waivers',     'waivers',     false, 5 * 1024 * 1024,
     array['application/pdf'])
on conflict (id) do nothing;

-------------------------------------------------------------------------------
-- avatars — owner writes, everyone reads
-------------------------------------------------------------------------------

create policy "avatars are readable"
  on storage.objects for select
  using (bucket_id = 'avatars');

create policy "users manage their own avatar"
  on storage.objects for all to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = app.current_user_id()::text
  )
  with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = app.current_user_id()::text
  );

-------------------------------------------------------------------------------
-- hike-photos & gpx — organizer of the hike writes, everyone reads
-------------------------------------------------------------------------------

create policy "hike media is readable"
  on storage.objects for select
  using (bucket_id in ('hike-photos', 'gpx'));

create policy "organizers manage media for their own hikes"
  on storage.objects for all to authenticated
  using (
    bucket_id in ('hike-photos', 'gpx')
    and app.is_organizer_of(((storage.foldername(name))[1])::uuid)
  )
  with check (
    bucket_id in ('hike-photos', 'gpx')
    and app.is_organizer_of(((storage.foldername(name))[1])::uuid)
  );

-------------------------------------------------------------------------------
-- waivers — private. The signer may read their own PDF; the organizer of the hike may
-- read the PDFs attached to their roster (FR-5.7). Writes are service-role only, because
-- the PDF is generated by the sign-waiver Edge Function.
-------------------------------------------------------------------------------

create policy "signers read their own waiver pdf"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'waivers'
    and (
      (storage.foldername(name))[1] = app.current_user_id()::text
      or app.is_admin()
      or exists (
        select 1
        from public.waivers w
        where w.pdf_url like '%' || storage.objects.name
          and app.is_organizer_of(w.hike_id)
      )
    )
  );
